var _g_aos_clsid_arr=[],_g_aos_mimetype_arr=[],_g_aos_opt_arr=[],_g_aos_cab_version="1,0,0,23",_g_aos_object_id="AOSMGR",_g_aos_object_name="AOSMGR",_g_aos_codebase="http://ahnlabdownload.nefficient.co.kr/aos/plugin/aosmgr.cab",_g_aos_ssl_codebase="https://secwebclinic.ahnlab.com/aos/plugin/aosmgr.cab",_g_aos_ff_installer="http://ahnlabdownload.nefficient.co.kr/aos/plugin/InstAosmgr.exe",_g_aos_ff_ssl_installer="https://secwebclinic.ahnlab.com/aos/plugin/InstAosmgr.exe",_g_aos_ff_installer_row="http://aspglobal.ahnlab.com/aos/plugin/InstAosmgr.exe",
_g_aos_ff_ssl_installer_row="http://aspglobal.ahnlab.com/aos/plugin/InstAosmgr.exe",_g_aos_ff_mimetype="application/ahnlab/asp/npaosmgr.1";_g_aos_opt_arr.authserver="webclinic.ahnlab.com";_g_aos_opt_arr.authinfo="";_g_aos_opt_arr.authrooturl="";_g_aos_opt_arr.asyncmode=!1;_g_aos_opt_arr.uimode=!0;_g_aos_opt_arr.browser=_aos_get_browser_type();_g_aos_opt_arr.codebase=_g_aos_codebase;_g_aos_opt_arr.ssl_codebase=_g_aos_ssl_codebase;_g_aos_opt_arr.ff_installer=_g_aos_ff_installer_row;
_g_aos_opt_arr.ff_ssl_installer=_g_aos_ff_ssl_installer_row;_g_aos_opt_arr.mkd_protect_level="default";_g_aos_opt_arr.obj_position="afterBegin";_g_aos_opt_arr.obj_style="";var g_firefox_install_running=!1,g_debug_enable=!1;
function check_support_firefox(){var a=!1;/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent)&&3<=new Number(RegExp.$1)&&(a=!0);if(!1==a){var b=document.charset;b&&"euc-kr"==b.toLowerCase()?alert("[AhnLab Online Security] Firefox 버전이 낮습니다. 최하 3.0 이상에서 사용할 수 있습니다."):alert("AhnLab Online Security does not support the current version of Firefox. You must upgrade the web browser to version 3.0 or greater.")}return a}
function check_support_opera(){var a=!1;/Version[\/\s](\d+\.\d+)/.test(navigator.userAgent)&&10<=new Number(RegExp.$1)&&(a=!0);if(!1==a){var b=document.charset;b&&"euc-kr"==b.toLowerCase()?alert("[AhnLab Online Security] Opera 버전이 낮습니다. 최하 10.0 이상에서 사용할 수 있습니다."):alert("AhnLab Online Security does not support the current version of Opera. You must upgrade the web browser to version 10.0 or greater.")}return a}
function check_support_safari(){var a=!1;/Version[\/\s](\d+\.\d+)/.test(navigator.userAgent)&&4<=new Number(RegExp.$1)&&(a=!0);if(!1==a){var b=document.charset;b&&"euc-kr"==b.toLowerCase()?alert("[AhnLab Online Security] Safari 버전이 낮습니다. 최하 4.0 이상에서 사용할 수 있습니다."):alert("AhnLab Online Security does not support the current version of Safari. You must upgrade the web browser to version 4.0 or greater.")}return a}
function check_support_chrome(){var a=!1;/Chrome[\/\s](\d+\.\d+)/.test(navigator.userAgent)&&2<=new Number(RegExp.$1)&&(a=!0);if(!1==a){var b=document.charset;b&&"euc-kr"==b.toLowerCase()?alert("[AhnLab Online Security] Chrome 버전이 낮습니다. 최하 2.0 이상에서 사용할 수 있습니다."):alert("AhnLab Online Security does not support the current version of Chrome. You must upgrade the web browser to version 2.0 or greater.")}return a}
function check_support_browser(){var a=navigator.userAgent,b=a.indexOf("Firefox"),c=a.indexOf("MSIE"),d=a.indexOf("Chrome"),e=a.indexOf("Safari");0<=e&&0<=a.indexOf("Chrome")&&(e=-1);var f=a.indexOf("Opera"),a=!0;if(0<=b)return check_support_firefox();if(0<=f)return check_support_opera();if(0<=e)return check_support_safari();if(0<=d)return check_support_chrome();0<=c||(a=!1);!1==a&&((b=document.charset)&&"euc-kr"==b.toLowerCase()?alert("[AhnLab Online Security] 지원하지 않는 웹브라우저입니다."):alert("[AhnLab Online Security] This web browser is not supported."));
return a}function check_support_os(){return-1==navigator.platform.indexOf("Win")?("euc-kr"==document.charset?alert("[AhnLab Online Security] 지원하지 않는 운영체제입니다."):alert("[AhnLab Online Security] This operating system is not supported."),!1):!0}function _aos_browser_version(a,b){var c=a.indexOf(b);if(-1!=c)return parseFloat(a.substring(c+b.length+1))}
function _aos_debug_print(a){!1!=g_debug_enable&&(!0==_aos_is_netscape()?document.body.innerHTML+=a+"<br>":document.body.insertAdjacentHTML("beforeEnd",a+"<br>"))}function onunload_handler(){}function onunload_check(){void 0==window.onunload&&(window.onunload=onunload_handler)}!0==_aos_is_netscape()&&onunload_check();function aos_set_authinfo(a){_g_aos_opt_arr.authinfo=a}function aos_set_auth_server(a){_g_aos_opt_arr.authserver=a}function aos_set_codebase(a){_g_aos_opt_arr.codebase=a}
function aos_set_xpi_codebase(){}function aos_set_ssl_codebase(a){_g_aos_ssl_codebase=a}function aos_set_ssl_xpi_codebase(){}function aos_set_xpi_installer(a){_g_aos_opt_arr.ff_installer=a}function aos_set_ssl_xpi_installer(a){_g_aos_opt_arr.ff_ssl_installer=a}function aos_set_subclsid(a,b){_g_aos_clsid_arr[a]=b}function aos_set_submimetype(a,b){_aos_set_submimetype(a,b)}function aos_set_option(a,b){_g_aos_opt_arr[a]=b}
function _aos_set_submimetype(a,b){_g_aos_mimetype_arr[a]="application/ahnlab/asp/npmkd25aos"==b?"application/ahnlab/asp/npmkd25sp":b}function _aos_write_object(){if(!1==check_support_os()||!1==check_support_browser())return!1;!1==_aos_is_netscape()?_aos_ie_write_object():_aos_ff_write_object()}
function _aos_ie_write_object(){if("x64"==clientInformation.cpuClass)return"euc-kr"==document.charset?alert(msg_browser_kr):alert(msg_browser_us),!1;var a=_g_aos_opt_arr.codebase;"https:"==document.location.protocol&&(a=_g_aos_ssl_codebase);var b="";"hideout"==_g_aos_opt_arr.obj_style&&(b="style='position:absolute;left=-1;top=-1'");document.body.insertAdjacentHTML(_g_aos_opt_arr.obj_position,"<OBJECT "+b+" classid='CLSID:063F7D71-5E0B-48F2-87D5-F63C5917947E' id='"+_g_aos_object_id+"' name='"+_g_aos_object_name+
"' height=0 width=0 tabindex=-1 codebase='"+a+"#version="+_g_aos_cab_version+"'></OBJECT>")}function _aos_ff_create_container(a){if(!document.getElementById(a)){var b=document.createElement("div");b.style.position="absolute";b.id=a;b.name=a;document.body.appendChild(b)}}function _aos_ff_create_write_object_container(){_aos_ff_create_container("AOSMGROBJCONTAINER");_aos_ff_create_container("MKD25OBJCONTAINER")}
function _aos_ff_write_object(a){"undefined"==typeof a&&(a=0);_aos_ff_create_write_object_container();if(_aos_ff_installed()){var b=document.getElementById("AOSMGR");if(null==b){var b="<OBJECT type='"+_g_aos_ff_mimetype+"' id='"+_g_aos_object_id+"' name='"+_g_aos_object_name+"' height=0 width=0 tabindex=-1></OBJECT>",c=document.getElementById("AOSMGROBJCONTAINER");c?c.innerHTML+=b:document.body.innerHTML+=b}!1==_aos_ff_loaded()&&(0<a&&((b=document.getElementById("AOSMGR"))&&b.parentNode.removeChild(b),
_aos_ff_install()),window.setTimeout("_aos_ff_write_object("+(a+1)+")",500))}else _aos_ff_install(),window.setTimeout("aos_write_object()",500)}function aos_write_object(){document.body?_aos_write_object():window.setTimeout("aos_write_object()",100)}function aos_start(a){window.setTimeout("_aos_start_onload('"+a+"')",100)}
function _aos_start(a){navigator.plugins.refresh(!1);var b=document.getElementById("AOSMGR");if(0<_aos_startcount())_aos_isfindlist(a,"40")&&_aos_startcount_wait_mkd();else{var c=_g_aos_opt_arr.asyncmode;if(0<_aos_frameindex()){if(c&&_aos_isfindlist(a,"e5"))return;if(_aos_isfindlist(a,"40")&&_aos_isrunning("40")){_aos_startcount_wait_mkd();return}}for(var d in _g_aos_opt_arr){if("undefined"==typeof _g_aos_opt_arr[d]){alert("invalid option ["+d+"]");return}b.setProperty(d,_g_aos_opt_arr[d])}b.setProperty("aos_event_handler",
_aos_event_handler);b.StartAos(a,0)}}function _aos_start_onload(a){_aos_loaded()&&0==_aos_startcount()?_aos_start(a):window.setTimeout("_aos_start_onload('"+a+"')",100)}function _aos_ff_install(){if(!0!=g_firefox_install_running){var a=_g_aos_opt_arr.ff_installer;"https:"==document.location.protocol&&(a=_g_aos_opt_arr.ff_ssl_installer);window.setTimeout("window.location.href = '"+a+"';",500);g_firefox_install_running=!0}}
function _aos_ff_installed(){navigator.plugins.refresh(!1);var a=_g_aos_ff_mimetype;return navigator.mimeTypes&&navigator.mimeTypes.length&&(a=navigator.mimeTypes[a])&&a.enabledPlugin?!0:!1}function _aos_ff_loaded(){var a=document.getElementById("AOSMGR");try{if("undefined"!=typeof a.IsRunning)return!0}catch(b){}return!1}function _aos_ie_loaded(){var a=document.getElementById("AOSMGR");try{if(a.object)return!0}catch(b){}return!1}function aos_loaded(){return _aos_loaded()}
function _aos_loaded(){return!0==_aos_is_netscape()?_aos_ff_loaded():_aos_ie_loaded()}function _aos_isfindlist(a,b){var c=!1;nIndex=a.indexOf(b);return c=-1==nIndex?!1:!0}function _aosak_ff_isvalid(){var a=_g_aos_mimetype_arr["40"];return navigator.mimeTypes&&navigator.mimeTypes.length&&(a=navigator.mimeTypes[a])&&a.enabledPlugin?!0:!1}
function _aos_event_handler(a,b,c,d){if("update_complete"==b){if(!0==_aos_isfindlist(c,"40")&&(!0==_aos_is_netscape()?_mkd_insert_ff_object(_g_aos_mimetype_arr["40"]):_mkd_insert_ie_object(_g_aos_clsid_arr["40"]),0<=navigator.userAgent.indexOf("Opera")||0<=navigator.userAgent.indexOf("Chrome")?!0==_aosak_ff_isvalid()?_mkd_start_onload():location.reload():_mkd_start_onload()),!0==_g_aos_opt_arr.asyncmode)return}else"update_event_begin"==b&&!0==_g_aos_opt_arr.asyncmode&&(b="update_complete");_g_aos_opt_arr.aos_event_handler&&
_g_aos_opt_arr.aos_event_handler(b,c,d)}function aos_get_text2(a){return document.getElementById("MKD25").GetText2(a)}function aos_get_param(a){return document.getElementById("MKD25").GetParam(a)}
function aos_copy_to_form(a){var b=_g_aos_opt_arr.mkd_protect_level;ownerDocument=a.ownerDocument;ownerDocument.getElementById("MKD25").SkipVerify(1);collObjects=a.getElementsByTagName("input");for(a=0;a<collObjects.length;a++)if("default"==b)"password"==collObjects[a].type&&(value=ownerDocument.getElementById("MKD25").GetText2(collObjects[a]),collObjects[a].value=value);else if("password"==collObjects[a].type||"text"==collObjects[a].type)value=ownerDocument.getElementById("MKD25").GetText2(collObjects[a]),
collObjects[a].value=value;ownerDocument.getElementById("MKD25").SkipVerify(0)}function aosak_insert_ie_object(a){return _mkd_insert_ie_object(a)}function _mkd_insert_ie_object(a){var b="";"hideout"==_g_aos_opt_arr.obj_style&&(b="style='position:absolute;left=-1;top=-1'");document.body.insertAdjacentHTML(_g_aos_opt_arr.obj_position,"<object "+b+" id='MKD25' name='MKD25' classid='clsid:"+a+"' height='0' width='0' tabindex='-1'></object>")}
function aosak_insert_ff_object(a){return _mkd_insert_ff_object(a)}function _mkd_insert_ff_object(a){var a="<OBJECT type='"+a+"' id='MKD25' name='MKD25' height=0 width=0 tabindex=-1></OBJECT>",b=document.getElementById("MKD25OBJCONTAINER");b?b.innerHTML+=a:document.body.innerHTML+=a}function _mkd_ie_installed(){try{if(MKD25.object)return!0}catch(a){}return!1}function _mkd_ff_installed(){return document.getElementById("MKD25")?!0:!1}function aosak_loaded(){return _mkd_loaded()}
function _mkd_loaded(){return!0==_aos_is_netscape()?_mkd_ff_installed():_mkd_ie_installed()}function _mkd_start(){var a=document.getElementById("MKD25"),b;for(b in _g_aos_opt_arr)"mkd_protect_level"==b?a.SetInitProtectLevel(_g_aos_opt_arr[b]):"mkd_"==b.substr(0,4)&&a.SetParam(b.substr(4,b.length-4),_g_aos_opt_arr[b]);a.Start()}function aosak_start_onload(){return _mkd_start_onload()}function _mkd_start_onload(){_mkd_loaded()?_mkd_start():window.setTimeout(_mkd_start_onload,100)}
function aos_start_ex(){_aos_loaded()&&0==_aos_startcount()?_aos_start_ex():window.setTimeout("aos_start_ex()",100)}
function _aos_start_ex(){if(0<_aos_startcount())_aos_startcount_wait_mkd();else{var a=_aos_isrunning("40"),b=a?0:_aos_checkupdate("40");if("undefined"==a||"undefined"==b)aos_set_option("uimode",!0),aos_set_option("asyncmode",!1),_aos_start("40|e5");else{var c=!1,d="",e=!1;a?(c=e=!0,d="e5"):b?(c=!1,d="40|e5"):(c=e=!0,d="e5");e&&(0==a&&_aos_start_lnchr(),_aos_startcount_wait_mkd());""!=d&&(aos_set_option("uimode",!c),aos_set_option("asyncmode",c),aos_start(d))}}}
function _aos_ie_is_new(){var a;try{if(a=new ActiveXObject("aosmgr.aosmgrCtrl.1"))return!0}catch(b){}return!1}function _aos_ff_is_new(){var a=_g_aos_ff_mimetype;return navigator.mimeTypes&&navigator.mimeTypes.length&&(a=navigator.mimeTypes[a])&&a.enabledPlugin?!0:!1}function aos_is_new(){return!0==_aos_is_netscape()?_aos_ff_is_new():_aos_ie_is_new()}
function aos_isinstalled(a){var b=document.getElementById("AOSMGR"),c=0;try{"undefined"!=typeof b.IsInstalled&&(c=b.IsInstalled(a))}catch(d){}return c}function aos_isrunning(a){return _aos_isrunning(a)}function _aos_isrunning(a){var b=document.getElementById("AOSMGR"),c=0;try{"undefined"!=typeof b.IsRunning&&(c=b.IsRunning(a))}catch(d){}return c}function aos_checkupdate(a){return _aos_checkupdate(a)}
function _aos_checkupdate(a){var b=document.getElementById("AOSMGR");if("undefined"==typeof b.CheckToUpdateEx)return"undefined";b.setProperty("authserver",_g_aos_opt_arr.authserver);b.setProperty("authrooturl",_g_aos_opt_arr.authrooturl);b.setProperty("authinfo",_g_aos_opt_arr.authinfo);var c=0;try{c=b.CheckToUpdateEx(a)}catch(d){}return c}function _aos_startcount(){var a=document.getElementById("AOSMGR"),b=0;try{"undefined"!=typeof a.StartCount&&(b=a.StartCount)}catch(c){}return b}
function _aos_frameindex(){var a=document.getElementById("AOSMGR"),b=0;try{"undefined"!=typeof a.FrameIndex&&(b=a.FrameIndex)}catch(c){}return b}function _aos_startcount_wait_mkd(){0==_aos_startcount()?(!0==_aos_is_netscape()?_mkd_insert_ff_object(_g_aos_mimetype_arr["40"]):_mkd_insert_ie_object(_g_aos_clsid_arr["40"]),_mkd_start_onload()):window.setTimeout(_aos_startcount_wait_mkd,100)}function aos_start_lnchr(){return _aos_start_lnchr()}
function _aos_start_lnchr(){var a=document.getElementById("AOSMGR"),b=0;try{"undefined"!=typeof a.StartLnchr&&(b=a.StartLnchr())}catch(c){}return b}function _aos_is_netscape(){return"Netscape"==navigator.appName||"Opera"==navigator.appName?!0:!1}function aos_common_js_ready(){}
function _aos_get_browser_type(){var a=navigator.userAgent;return 0<=a.indexOf("MSIE")?"iexplore":0<=a.indexOf("Firefox")?"firefox":0<=a.indexOf("Chrome")?"chrome":0<=a.indexOf("Safari")?"safari":0<=a.indexOf("Opera")?"opera":"unknown"}function aos_set_cookie(a,b){var c=document.getElementById("AOSMGR");if("undefined"!=typeof c.setProperty)try{c.setProperty("cookie_domain",a?a:document.domain),c.setProperty("cookie_value",b?b:document.cookie)}catch(d){}};