<!-- menu -->
<ul class="menu">
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
    <li><a href="#">游戏下载</a></li>
</ul>
<!-- menu end -->
<!-- tools -->
<div class="tools">
    <p>
        <span>新手：</span>
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a>
    </p>
    <p>
        <span>工具：</span>
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a>
        <span>工具：</span>
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a> |
        <a href="#">游戏下载</a>
    </p>
</div>
<!-- tools end -->
<!-- search -->
<div class="search">
    <h3>文章搜索：</h3>
    <input type="text" class="intxt" value="请输入查找的关键字" onFocus="if(this.value=='请输入查找的关键字')this.value='';;" onBlur="if(this.value==''){this.value='请输入查找的关键字';}" />
    <input type="submit" value="搜索" class="inss">
</div>
<!-- search end -->