<div class="fullbg">
    <!-- wrapper -->
    <div class="wrapper">
        <div class="header"></div>
        <!-- nav -->
        <div class="nav">
            <a href="#" class="a1" hidefocus="true">专区首页</a>
            <a href="#" class="a2" hidefocus="true">攻略站</a>
            <a href="#" class="a3" hidefocus="true">视频站</a>
            <a href="#" class="a4" hidefocus="true">图片站</a>
            <a href="#" class="a5" hidefocus="true">实用工具</a>
            <a href="#" class="a6" hidefocus="true">进入论坛</a>
        </div>
        <!-- nav end -->