<!-- sider -->
<div class="sider">
    <!-- column2 -->
    <div class="column2 bd1 m0">
        <h3><a href="#" class="more">more</a><span>职业攻略</span></h3>
        <div class="bd2 pd10">
            <ul class="list">
                <!--CPLoopStart-->
                <li><a href="<!--CPUrl-->"><!--CPTitle--></a></li>
                 <!--CPLoopEnd-->
                <li class="line"></li>
                 <!--CPLoopStart-->
                <li><a href="<!--CPUrl-->"><!--CPTitle--></a></li>
                 <!--CPLoopEnd-->
                <li class="line"></li>
                <!--CPLoopStart-->
                <li><a href="<!--CPUrl-->"><!--CPTitle--></a></li>
                <!--CPLoopEnd-->
            </ul>
        </div>
        <h3><a href="#" class="more">more</a><span>职业攻略</span></h3>
        <div class="bd2">
            <ul class="piclist2 clearfix">
                <!--CPLoopStart-->
                <li><a href="<!--CPUrl-->"><img src="<!--CPPicUrl-->"><p><!--CPTitle--> </p></a></li>
                <!--CPLoopEnd-->
            </ul>
        </div>
        <h3><a href="#" class="more">more</a><span>职业攻略</span></h3>
        <div class="bd2 pd10">
            <ul class="list">
                 <!--CPLoopStart-->
                 <li><a href="<!--CPUrl-->"><!--CPTitle--></a></li>
                <!--CPLoopEnd-->
                <li class="line"></li>
                 <!--CPLoopStart-->
                 <li><a href="<!--CPUrl-->"><!--CPTitle--></a></li>
                <!--CPLoopEnd-->
            </ul>
        </div>
        <h3><a href="#" class="more">more</a><span>职业攻略</span></h3>
        <div class="bd2">
            <ul class="piclist2 clearfix">
                <!--CPLoopStart-->
                <li><a href="<!--CPUrl-->"><img src="<!--CPPicUrl-->"><p><!--CPTitle--></p></a></li>
                <!--CPLoopEnd-->
            </ul>
        </div>
    </div>
    <!-- column2 end -->
</div>