_skill_zero: "無",
_pre_cancel: "キャンセル",
_unnamed_cancel_skill: "キャンセルスキル(名称未設定)",
_post_ex   : "強化",
_unnamed_ex: "Exスキル(名称未設定)",
_unnamed   : "名称未設定",
_pre_requirements: "前提スキル",
_quest_name : "クエスト名",
_clear_cookie_msg : "Cookieを削除しますか?\n(全ての保存されているデータが削除されます)",
_save_slot_msg : "スロットNo.#{slot_no}にセーブします．\nタイトルを入力してください．",
_load_slot_msg : "スロットNo.#{slot_no}を読み込みますか?",
_clear_form_msg: "現在のスキル情報をリセットしますか?\n(保存されている情報に変更はありません)",
_contracted : "契約",
_rested_sp : "余りSP",
_rested_tp : "余りTP",
_do_decode_msg : "スキルコードを復元しますか?(現在の設定は破棄されます)",
_newer_msg : "最新版有〼",
